language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy3"

sudo: false

install:
  - pip install -r requirements.txt

before_script:
  - flake8 --max-line-length=99 .

script:
  - nosetests --rednose --with-coverage --cover-package exlogging
