language: python
python:
  - "3.4"

sudo: false

install:
  - pip install -r requirements

before_script:
  - flake8 --max-line-length=99 .

script:
  - nosetests --rednose --with-coverage --cover-package blogging
